# This workflow installs dependencies, run unit tests and run lint when code is pushed to feature branch.

name: Push to Feature Branch

on:
  push:
    branches: [ issue-** ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test:unit
    - run: npm run lint -- --no-fix