name: Push to master

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test:unit
      - name: Lint
        run: npm run lint -- --no-fix --max-warnings 1
      - name: Build
        run: npm run build
      - name: Package
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/**/*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Unpackage
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Deploy to S3
        run: |
          echo "Deploy dist folder to S3"
          ls -R
